Document: lessedit
Title: Debian lessedit Manual
Author: <insert document author here>
Abstract: This manual describes what lessedit is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lessedit/lessedit.sgml.gz

Format: postscript
Files: /usr/share/doc/lessedit/lessedit.ps.gz

Format: text
Files: /usr/share/doc/lessedit/lessedit.text.gz

Format: HTML
Index: /usr/share/doc/lessedit/html/index.html
Files: /usr/share/doc/lessedit/html/*.html
